// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOukgLVoSxrg1VhysVjJXBeIgI4DTUGM',
    appId: '1:680664776734:web:a89728d31217f2a4ddae0f',
    messagingSenderId: '680664776734',
    projectId: 'devproject-ef3c6',
    authDomain: 'devproject-ef3c6.firebaseapp.com',
    storageBucket: 'devproject-ef3c6.firebasestorage.app',
    measurementId: 'G-ML26BQDCKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRn3Se3TTOvzflzlwL8GszToiwYg8zLSM',
    appId: '1:680664776734:android:a7c4da24bfdc7942ddae0f',
    messagingSenderId: '680664776734',
    projectId: 'devproject-ef3c6',
    storageBucket: 'devproject-ef3c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjtvKTMco2OvUAHRoZynvffNE6GaAlo1M',
    appId: '1:680664776734:ios:d7013fb7fe2960f9ddae0f',
    messagingSenderId: '680664776734',
    projectId: 'devproject-ef3c6',
    storageBucket: 'devproject-ef3c6.firebasestorage.app',
    iosBundleId: 'com.example.devProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjtvKTMco2OvUAHRoZynvffNE6GaAlo1M',
    appId: '1:680664776734:ios:d7013fb7fe2960f9ddae0f',
    messagingSenderId: '680664776734',
    projectId: 'devproject-ef3c6',
    storageBucket: 'devproject-ef3c6.firebasestorage.app',
    iosBundleId: 'com.example.devProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASOukgLVoSxrg1VhysVjJXBeIgI4DTUGM',
    appId: '1:680664776734:web:8231d603e128fabfddae0f',
    messagingSenderId: '680664776734',
    projectId: 'devproject-ef3c6',
    authDomain: 'devproject-ef3c6.firebaseapp.com',
    storageBucket: 'devproject-ef3c6.firebasestorage.app',
    measurementId: 'G-Y3V0397YHT',
  );
}
